Add methods about invitations in auth-server in Litmus
litmuschaos/litmus-java-sdk pull request #29
Opened 2024-11-14 18:22 UTC by inpyu

I created methods that wraps APIs related to invite
And, I also implemented test code and Docs for these APIs.

2024-11-14 18:23 UTC, inpyu commented
@suyeon-jung-dev @jemlog @seedspirit Can you please take a look?

2024-11-15 06:53 UTC, seedspirit commented
LGTM 👍

2024-11-15 08:22 UTC, jemlog approved these changes
Nice work @inpyu !
Your documentation is so helpful 👍

2024-11-15 08:22 UTC, jemlog commented on src/test/java/InviteTest.java
> +                .build();
Can you remove console print method? 🙂

2024-11-15 08:22 UTC, jemlog commented on src/test/java/InviteTest.java
> +        ProjectResponse projectResponse = litmusClient.createProject(projectRequest);
I think we need to remove created project after test finished for independent tests.

2024-11-15 09:12 UTC, suyeon-jung-dev requested changes
Great work @inpyu ! 👍👍 I’ve left comments for one class, but could you review and apply similar improvements across the other classes as well?

2024-11-15 09:12 UTC, suyeon-jung-dev commented on src/main/java/io/litmuschaos/request/AcceptInvitationRequest.java
> +    }
Could you implements Builder class in `io.litmuschaos.util.Builder`?

2024-11-15 09:12 UTC, suyeon-jung-dev commented on src/main/java/io/litmuschaos/request/AcceptInvitationRequest.java
> +    private String userId;
Could you consider making these fields `final` to ensure immutability?

```java
private final String projectId;
private final String userId;

2024-11-16 14:21 UTC, inpyu commented on src/test/java/InviteTest.java
> +                .build();
Oh, I didn't check it. thanks!

2024-11-16 15:02 UTC, inpyu commented
I've updated the Invite Client Code. thanks for your kind example!  Could you please review it? @suyeon-jung-dev @jemlog

2024-11-16 15:38 UTC, jemlog commented
👍

2024-11-17 11:55 UTC, merged