refactor: replace strings with constant values
litmuschaos/litmus-java-sdk pull request #39
Opened 2024-12-15 02:04 UTC by seedspirit

Replaced all strings to constant values. String constants values are located in io/litmuschaos/constants directory

2024-12-15 08:16 UTC, namkyu1999 approved these changes

2024-12-17 03:48 UTC, seedspirit commented
@jemlog I realized I missed the invitation api. Made commit to reflect it

2024-12-17 06:18 UTC, jemlog commented
LGTM!

2024-12-17 06:50 UTC, namkyu1999 requested changes

2024-12-17 06:50 UTC, namkyu1999 commented on src/main/java/io/litmuschaos/LitmusClient.java
> +    public String authenticate(LoginRequest request)
could you make a token class instead of returing string? it's for maintanence

2024-12-23 11:07 UTC, namkyu1999 requested changes

2024-12-23 11:07 UTC, namkyu1999 commented on src/main/java/io/litmuschaos/LitmusClient.java
> +    public LitmusClient(String host, LitmusAuthToken token) {
```suggestion
    public LitmusClient(String host, String token) {
```

Can you get token as string and make like below?

this.token = new ListAuthToken(token);

2024-12-23 11:07 UTC, namkyu1999 commented on src/main/java/io/litmuschaos/LitmusClient.java
> +        LoginResponse response = httpClient.post(LOGIN, request, LoginResponse.class);
Is this code actually working?

2025-01-02 13:49 UTC, namkyu1999 approved these changes

2025-01-02 13:49 UTC, merged